# ziye
# github地址  https://github.com/6Svip120apk69
# TG频道地址  https://t.me/ziyescript
# TG交流群    https://t.me/joinchat/AAAAAE7XHm-q1-7Np-tF3g
# boxjs链接   https://raw.githubusercontent.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE/main/Task/ziye.boxjs.json



# ⚠️⚠️⚠️特别重要,务必进行替换操作，不得使用原作者地址

# 具体方法请看: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions



#  以账号    aaa
#  仓库地址  https://github.com/aaa/bbb 
#  文件地址   https://raw.githubusercontent.com/aaa/bbb/ZIYE/Task/xiaole.js    为例 


# 主要替换的字符👇

# 小乐     //js名字
# 0 0-15   //定时，如北京时间8到23点，设置0-15
# XL_URL   //环境变量之一，47行处自行添加其他
# aaa      //账号名
# bbb      //仓库名
# ZIYE     //分支名
# Task/xiaole.js  //子文件地址




name: 书旗小说

on:
  workflow_dispatch:
  schedule:
     - cron: '0,30 0-14,16 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        SQ_shuqiuserURL: ${{ secrets.SQ_shuqiuserURL }}
        SQ_shuqisyURL: ${{ secrets.SQ_shuqisyURL }}
        SQ_shuqisyBODY: ${{ secrets.SQ_shuqisyBODY }}
        SQ_shuqispBODY: ${{ secrets.SQ_shuqispBODY }}
        SQ_shuqiscBODY: ${{ secrets.Q_shuqiscBODY }}
        SQ_shuqiydBODY: ${{ secrets.SQ_shuqiydBODY }}
        SQ_shuqiqdBODY: ${{ secrets.SQ_shuqiqdBODY }}
        SQ_shuqirwBODY: ${{ secrets.SQ_shuqirwBODY }}
        SQ_shuqifxBODY: ${{ secrets.SQ_shuqifxBODY }}
        SQ_shuqisprwURL: ${{ secrets.SQ_shuqisprwURL }}
        SQ_shuqijlBODY: ${{ secrets.SQ_shuqijlBODY }}
        SQ_shuqisqjlBODY: ${{ secrets.SQ_shuqisqjlBODY }}
        SQ_shuqicjyURL: ${{ secrets.SQ_shuqicjyURL }}
        SQ_shuqicjcsBODY: ${{ secrets.SQ_shuqicjcsBODY }}
        SQ_shuqicjBODY: ${{ secrets.SQ_shuqicjBODY }}
        SQ_shuqijsspBODY: ${{ secrets.SQ_shuqijsspBODY }}
        SQ_shuqijsydURL: ${{ secrets.SQ_shuqijsydURL }}
        SQ_shuqijsydBODY: ${{ secrets.SQ_shuqijsydBODY }}
        SQ_shuqijsqdBODY: ${{ secrets.SQ_shuqijsqdBODY }}
        SQ_shuqijsqdspyURL: ${{ secrets.SQ_shuqijsqdspyURL }}
        SQ_shuqijsqdspBODY: ${{ secrets.SQ_shuqijsqdspBODY }}
        SQ_shuqijsrwBODY: ${{ secrets.SQ_shuqijsrwBODY }}
        SQ_shuqijsfxBODY: ${{ secrets.SQ_shuqijsfxBODY }}
        SQ_shuqijsbookURL: ${{ secrets.SQ_shuqijsbookURL }}
        SQ_shuqijsbookBODY: ${{ secrets.SQ_shuqijsbookBODY }}
        SQ_shuqijssprwURL: ${{ secrets.SQ_shuqijssprwURL }}
        
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/208249775/AutoSyncScript.git ~/AutoSyncScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.SQ_shuqiuserURL
        run: |
          cd ~/AutoSyncScript
          git checkout ZIYE
          npm install
      - name: '运行 【书旗小说】'
        if: env.SQ_shuqiuserURL
        run: |
          cd ~/AutoSyncScript
          node Task/shuqi.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
